// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7SKXRklQwN7bQ5W0YVnYaWTFXmyAWrPs',
    appId: '1:230963473049:web:b73c22775d3b3d720be608',
    messagingSenderId: '230963473049',
    projectId: 'paymuster-dev',
    authDomain: 'paymuster-dev.firebaseapp.com',
    storageBucket: 'paymuster-dev.firebasestorage.app',
    measurementId: 'G-R1T4RMVRXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZrdZIgaxFDvRjUwHTr58P6cirV4txImA',
    appId: '1:230963473049:android:bd25c19b9f78bd390be608',
    messagingSenderId: '230963473049',
    projectId: 'paymuster-dev',
    storageBucket: 'paymuster-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqwuuSp6Sg-YRoOyJGQ9Meg4Yl-ML_1qw',
    appId: '1:230963473049:ios:2b2a682b15edb0e90be608',
    messagingSenderId: '230963473049',
    projectId: 'paymuster-dev',
    storageBucket: 'paymuster-dev.firebasestorage.app',
    iosBundleId: 'com.example.paymusterMobile',
  );
}
