export type Language = 'en' | 'hi' | 'pa';

export const languageLabels: Record<Language, string> = { en: 'English', hi: 'हिन्दी', pa: 'ਪੰਜਾਬੀ' };

export const messages: Record<Language, Record<string, string>> = {
  en: {
    'language.label': 'Language', 'theme.label': 'Theme', 'theme.dark': 'Dark', 'theme.light': 'Light', 'theme.amoled': 'AMOLED', 'theme.system': 'System',
'nav.overview': 'Overview', 'nav.workforce': 'Workforce', 'nav.sites': 'Sites', 'nav.attendance': 'Attendance', 'nav.payroll': 'Payroll', 'nav.ownerRequests': 'Owner Requests', 'nav.ai': 'AI Assistant', 'nav.workforceOs': 'Workforce OS', 'nav.today': 'Today', 'nav.projectPulse': 'Project pulse', 'nav.openCommandCenter': 'Open command center', 'nav.approvalsSummary': '11 approvals pending · 4 sites active',
    'topbar.goodEvening': 'Good evening', 'topbar.controlCenter': 'Operational control center', 'topbar.search': 'Search workforce', 'topbar.sync': 'Sync now',
    'dashboard.operatingSystem': 'Workforce operating system', 'dashboard.heroTitle': 'The calm control layer for the modern jobsite.', 'dashboard.heroDescription': 'Premium operations, field-ready sync, and AI-guided clarity for every crew, site, and approval.', 'dashboard.reviewToday': 'Review today', 'dashboard.openAi': 'Open AI assistant', 'dashboard.siteHealth': 'Site health', 'dashboard.liveSnapshot': 'Live readiness snapshot', 'dashboard.stable': 'Stable', 'dashboard.crewCommute': 'Crew commute', 'dashboard.materials': 'Materials', 'dashboard.equipment': 'Equipment', 'dashboard.todayWorkforce': 'Today\'s workforce', 'dashboard.timelineDescription': 'A premium timeline view for crews and approvals', 'dashboard.openTimeline': 'Open timeline', 'dashboard.attendance': 'Attendance', 'dashboard.attendanceSynced': 'Attendance synced', 'dashboard.approvalPending': 'Approval pending', 'dashboard.payroll': 'Payroll', 'dashboard.payrollReview': 'Payroll review', 'dashboard.crewCheckedIn': 'Crew A · 24 checked in', 'dashboard.materialRequest': 'Materials request · Site 12', 'dashboard.weeklyRunReady': 'Weekly run ready', 'dashboard.aiInsight': 'AI insight', 'dashboard.aiDescription': 'Refined for operators, not gimmicks', 'dashboard.live': 'Live', 'dashboard.aiMessage': 'Two crews will likely exceed overtime thresholds by 2.6% this week. Recommend a dispatch adjustment.',
    'metric.workersPresent': 'Workers present', 'metric.payrollDue': 'Payroll due', 'metric.sitesHealthy': 'Sites healthy', 'metric.expenses': 'Expenses', 'metric.pending': '4 pending', 'metric.alerts': '3 alerts', 'metric.today': 'Today', 'common.view': 'View', 'common.createFirstItem': 'Create first item',
    'admin.ownerRequests': 'Owner Requests', 'admin.ownerRequestsTitle': 'Owner Requests', 'admin.ownerRequestsDescription': 'Review and manage owner verification requests.', 'admin.totalRequests': 'Total Requests', 'admin.pending': 'Pending', 'admin.approved': 'Approved', 'admin.requestsList': 'Requests List', 'admin.requestsListDescription': 'All owner requests with approve and reject actions.', 'admin.approve': 'Approve', 'admin.reject': 'Reject', 'admin.noPendingRequests': 'No pending requests.',
    'admin.userProfile': 'User Profile', 'admin.userProfileTitle': 'User Profile', 'admin.userDetails': 'User Details', 'admin.name': 'Name', 'admin.email': 'Email', 'admin.publicId': 'Public ID', 'admin.role': 'Role', 'admin.status': 'Status', 'admin.lastLogin': 'Last Login', 'admin.actions': 'Actions', 'admin.actionsDescription': 'Perform administrative actions on this user.', 'admin.activate': 'Activate', 'admin.suspend': 'Suspend', 'admin.resetPassword': 'Reset Password', 'admin.sendEmail': 'Send Email', 'admin.actionSuccess': 'Action succeeded', 'admin.actionFailed': 'Action failed',
    'admin.userSearch': 'User Search', 'admin.userSearchTitle': 'User Search', 'admin.userSearchDescription': 'Search for users by name, public ID, or email.', 'admin.searchPlaceholder': 'Search users...', 'admin.search': 'Search', 'admin.searching': 'Searching...', 'admin.searchResults': 'Search Results', 'admin.usersFound': 'users found', 'admin.noUsersFound': 'No users found.',
    'admin.attendanceRecords': 'Attendance Records', 'admin.attendanceDescription': 'View and manage attendance records.', 'admin.attendanceList': 'Attendance List', 'admin.attendanceListDescription': 'Current attendance records for all workers.', 'admin.present': 'Present', 'admin.late': 'Late', 'admin.absent': 'Absent',
    'admin.payrollRecords': 'Payroll Records', 'admin.payrollDescription': 'View and manage payroll records.', 'admin.payrollList': 'Payroll List', 'admin.payrollListDescription': 'Payroll records for the current period.', 'admin.totalPayroll': 'Total Payroll', 'admin.paid': 'Paid',
    'session.restoring': 'Restoring your secure session…', 'session.signedInAs': 'Signed in as', 'session.signOut': 'Sign out', 'session.signingOut': 'Signing out…',
  },
  hi: {
    'language.label': 'भाषा', 'theme.label': 'थीम', 'theme.dark': 'डार्क', 'theme.light': 'लाइट', 'theme.amoled': 'AMOLED', 'theme.system': 'सिस्टम',
    'nav.overview': 'अवलोकन', 'nav.workforce': 'कार्यबल', 'nav.sites': 'साइट', 'nav.attendance': 'हाज़री', 'nav.payroll': 'पेरोल', 'nav.ownerRequests': 'मालिक अनुरोध', 'nav.ai': 'AI सहायक', 'nav.workforceOs': 'कार्यबल OS', 'nav.today': 'आज', 'nav.projectPulse': 'प्रोजेक्ट स्थिति', 'nav.openCommandCenter': 'कमांड सेंटर खोलें', 'nav.approvalsSummary': '11 अनुमोदन लंबित · 4 साइट सक्रिय',
    'topbar.goodEvening': 'शुभ संध्या', 'topbar.controlCenter': 'ऑपरेशनल कंट्रोल सेंटर', 'topbar.search': 'कार्यबल खोजें', 'topbar.sync': 'अभी सिंक करें',
    'dashboard.operatingSystem': 'कार्यबल ऑपरेटिंग सिस्टम', 'dashboard.heroTitle': 'आधुनिक जॉबसाइट के लिए शांत नियंत्रण केंद्र।', 'dashboard.heroDescription': 'हर टीम, साइट और अनुमोदन के लिए प्रीमियम ऑपरेशन, फील्ड-रेडी सिंक और AI मार्गदर्शन।', 'dashboard.reviewToday': 'आज की समीक्षा करें', 'dashboard.openAi': 'AI सहायक खोलें', 'dashboard.siteHealth': 'साइट स्थिति', 'dashboard.liveSnapshot': 'लाइव तैयारी सारांश', 'dashboard.stable': 'स्थिर', 'dashboard.crewCommute': 'टीम आवागमन', 'dashboard.materials': 'सामग्री', 'dashboard.equipment': 'उपकरण', 'dashboard.todayWorkforce': 'आज का कार्यबल', 'dashboard.timelineDescription': 'टीम और अनुमोदन की टाइमलाइन', 'dashboard.openTimeline': 'टाइमलाइन खोलें', 'dashboard.attendanceSynced': 'उपस्थिति सिंक हुई', 'dashboard.approvalPending': 'अनुमोदन लंबित', 'dashboard.payrollReview': 'पेरोल समीक्षा', 'dashboard.crewCheckedIn': 'टीम A · 24 उपस्थित', 'dashboard.materialRequest': 'सामग्री अनुरोध · साइट 12', 'dashboard.weeklyRunReady': 'साप्ताहिक रन तैयार', 'dashboard.aiInsight': 'AI जानकारी', 'dashboard.aiDescription': 'ऑपरेटरों के लिए स्पष्ट और उपयोगी', 'dashboard.live': 'लाइव', 'dashboard.aiMessage': 'इस सप्ताह दो टीमें ओवरटाइम सीमा से 2.6% अधिक जा सकती हैं। डिस्पैच समायोजन सुझाया गया है।',
    'metric.workersPresent': 'उपस्थित कर्मचारी', 'metric.payrollDue': 'पेरोल देय', 'metric.sitesHealthy': 'सक्रिय साइट', 'metric.expenses': 'खर्च', 'metric.pending': '4 लंबित', 'metric.alerts': '3 अलर्ट', 'metric.today': 'आज', 'common.view': 'देखें', 'common.createFirstItem': 'पहली प्रविष्टि बनाएँ',
    'admin.ownerRequests': 'मालिक अनुरोध', 'admin.ownerRequestsTitle': 'मालिक अनुरोध', 'admin.ownerRequestsDescription': 'मालिक सत्यापन अनुरोधों की समीक्षा और प्रबंधन करें।', 'admin.totalRequests': 'कुल अनुरोध', 'admin.pending': 'लंबित', 'admin.approved': 'अनुमोदित', 'admin.requestsList': 'अनुरोध सूची', 'admin.requestsListDescription': 'सभी मालिक अनुरोधों को अनुमोदित और अस्वीकार करने की क्रियाएँ।', 'admin.approve': 'अनुमोदित करें', 'admin.reject': 'अस्वीकार करें', 'admin.noPendingRequests': 'कोई लंबित अनुरोध नहीं।',
    'admin.userProfile': 'उपयोगकर्ता प्रोफ़ाइल', 'admin.userProfileTitle': 'उपयोगकर्ता प्रोफ़ाइल', 'admin.userDetails': 'उपयोगकर्ता विवरण', 'admin.name': 'नाम', 'admin.email': 'ईमेल', 'admin.publicId': 'सार्वजनिक ID', 'admin.role': 'भूमिका', 'admin.status': 'स्थिति', 'admin.lastLogin': 'अंतिम लॉगिन', 'admin.actions': 'क्रियाएँ', 'admin.actionsDescription': 'इस उपयोगकर्ता पर प्रशासनिक क्रियाएँ करें।', 'admin.activate': 'सक्रिय करें', 'admin.suspend': 'निलंबित करें', 'admin.resetPassword': 'पासवर्ड रीसेट करें', 'admin.sendEmail': 'ईमेल भेजें', 'admin.actionSuccess': 'क्रिया सफल रही', 'admin.actionFailed': 'क्रिया विफल रही',
    'admin.userSearch': 'उपयोगकर्ता खोज', 'admin.userSearchTitle': 'उपयोगकर्ता खोज', 'admin.userSearchDescription': 'नाम, सार्वजनिक ID या ईमेल द्वारा उपयोगकर्ताओं की खोज करें।', 'admin.searchPlaceholder': 'उपयोगकर्ता खोजें...', 'admin.search': 'खोजें', 'admin.searching': 'खोज रहे हैं...', 'admin.searchResults': 'खोज परिणाम', 'admin.usersFound': 'उपयोगकर्ता मिले', 'admin.noUsersFound': 'कोई उपयोगकर्ता नहीं मिला।',
    'admin.attendanceRecords': 'हाज़री रिकॉर्ड', 'admin.attendanceDescription': 'हाज़री रिकॉर्ड देखें और प्रबंधित करें।', 'admin.attendanceList': 'हाज़री सूची', 'admin.attendanceListDescription': 'सभी कार्यकर्ताओं के लिए वर्तमान हाज़री रिकॉर्ड।', 'admin.present': 'मौजूद', 'admin.late': 'देर से', 'admin.absent': 'अनुपस्थित',
    'admin.payrollRecords': 'पेरोल रिकॉर्ड', 'admin.payrollDescription': 'पेरोल रिकॉर्ड देखें और प्रबंधित करें।', 'admin.payrollList': 'पेरोल सूची', 'admin.payrollListDescription': 'वर्तमान अवधि के लिए पेरोल रिकॉर्ड।', 'admin.totalPayroll': 'कुल पेरोल', 'admin.paid': 'भुगतान किया गया',
    'session.restoring': 'आपका सुरक्षित सत्र पुनर्स्थापित हो रहा है…', 'session.signedInAs': 'के रूप में साइन इन', 'session.signOut': 'साइन आउट', 'session.signingOut': 'साइन आउट हो रहा है…',
  },
  pa: {
    'language.label': 'ਭਾਸ਼ਾ', 'theme.label': 'ਥੀਮ', 'theme.dark': 'ਡਾਰਕ', 'theme.light': 'ਲਾਈਟ', 'theme.amoled': 'AMOLED', 'theme.system': 'ਸਿਸਟਮ',
    'nav.overview': 'ਝਲਕ', 'nav.workforce': 'ਕਰਮਚਾਰੀ', 'nav.sites': 'ਸਾਈਟਾਂ', 'nav.payroll': 'ਤਨਖਾਹ', 'nav.ai': 'AI ਸਹਾਇਕ', 'nav.workforceOs': 'ਕਰਮਚਾਰੀ OS', 'nav.today': 'ਅੱਜ', 'nav.projectPulse': 'ਪ੍ਰੋਜੈਕਟ ਸਥਿਤੀ', 'nav.openCommandCenter': 'ਕਮਾਂਡ ਸੈਂਟਰ ਖੋਲ੍ਹੋ', 'nav.approvalsSummary': '11 ਮਨਜ਼ੂਰੀਆਂ ਲੰਬਿਤ · 4 ਸਾਈਟਾਂ ਸਰਗਰਮ',
    'topbar.goodEvening': 'ਸ਼ੁਭ ਸ਼ਾਮ', 'topbar.controlCenter': 'ਓਪਰੇਸ਼ਨਲ ਕੰਟਰੋਲ ਸੈਂਟਰ', 'topbar.search': 'ਕਰਮਚਾਰੀ ਲੱਭੋ', 'topbar.sync': 'ਹੁਣੇ ਸਿੰਕ ਕਰੋ',
    'dashboard.operatingSystem': 'ਕਰਮਚਾਰੀ ਓਪਰੇਟਿੰਗ ਸਿਸਟਮ', 'dashboard.heroTitle': 'ਆਧੁਨਿਕ ਜੌਬਸਾਈਟ ਲਈ ਸ਼ਾਂਤ ਕੰਟਰੋਲ ਪਰਤ।', 'dashboard.heroDescription': 'ਹਰ ਟੀਮ, ਸਾਈਟ ਅਤੇ ਮਨਜ਼ੂਰੀ ਲਈ ਪ੍ਰੀਮੀਅਮ ਓਪਰੇਸ਼ਨ, ਫੀਲਡ-ਤਿਆਰ ਸਿੰਕ ਅਤੇ AI ਮਾਰਗਦਰਸ਼ਨ।', 'dashboard.reviewToday': 'ਅੱਜ ਦੀ ਸਮੀਖਿਆ ਕਰੋ', 'dashboard.openAi': 'AI ਸਹਾਇਕ ਖੋਲ੍ਹੋ', 'dashboard.siteHealth': 'ਸਾਈਟ ਸਥਿਤੀ', 'dashboard.liveSnapshot': 'ਲਾਈਵ ਤਿਆਰੀ ਸਾਰ', 'dashboard.stable': 'ਸਥਿਰ', 'dashboard.crewCommute': 'ਟੀਮ ਆਵਾਜਾਈ', 'dashboard.materials': 'ਸਮੱਗਰੀ', 'dashboard.equipment': 'ਸਾਜ਼ੋ-ਸਾਮਾਨ', 'dashboard.todayWorkforce': 'ਅੱਜ ਦਾ ਕਰਮਚਾਰੀ ਦਲ', 'dashboard.timelineDescription': 'ਟੀਮਾਂ ਅਤੇ ਮਨਜ਼ੂਰੀਆਂ ਦੀ ਟਾਈਮਲਾਈਨ', 'dashboard.openTimeline': 'ਟਾਈਮਲਾਈਨ ਖੋਲ੍ਹੋ', 'dashboard.attendanceSynced': 'ਹਾਜ਼ਰੀ ਸਿੰਕ ਹੋਈ', 'dashboard.approvalPending': 'ਮਨਜ਼ੂਰੀ ਲੰਬਿਤ', 'dashboard.payrollReview': 'ਤਨਖਾਹ ਸਮੀਖਿਆ', 'dashboard.crewCheckedIn': 'ਟੀਮ A · 24 ਹਾਜ਼ਰ', 'dashboard.materialRequest': 'ਸਮੱਗਰੀ ਬੇਨਤੀ · ਸਾਈਟ 12', 'dashboard.weeklyRunReady': 'ਹਫ਼ਤਾਵਾਰੀ ਰਨ ਤਿਆਰ', 'dashboard.aiInsight': 'AI ਜਾਣਕਾਰੀ', 'dashboard.aiDescription': 'ਆਪਰੇਟਰਾਂ ਲਈ ਸਾਫ਼ ਅਤੇ ਲਾਭਦਾਇਕ', 'dashboard.live': 'ਲਾਈਵ', 'dashboard.aiMessage': 'ਇਸ ਹਫ਼ਤੇ ਦੋ ਟੀਮਾਂ ਓਵਰਟਾਈਮ ਹੱਦ ਤੋਂ 2.6% ਵੱਧ ਜਾ ਸਕਦੀਆਂ ਹਨ। ਡਿਸਪੈਚ ਬਦਲਾਅ ਦੀ ਸਿਫ਼ਾਰਸ਼ ਹੈ।',
    'metric.workersPresent': 'ਹਾਜ਼ਰ ਕਰਮਚਾਰੀ', 'metric.payrollDue': 'ਤਨਖਾਹ ਬਕਾਇਆ', 'metric.sitesHealthy': 'ਸਰਗਰਮ ਸਾਈਟਾਂ', 'metric.expenses': 'ਖਰਚੇ', 'metric.pending': '4 ਲੰਬਿਤ', 'metric.alerts': '3 ਚੇਤਾਵਨੀਆਂ', 'metric.today': 'ਅੱਜ', 'common.view': 'ਵੇਖੋ', 'common.createFirstItem': 'ਪਹਿਲੀ ਐਂਟਰੀ ਬਣਾਓ',
    'admin.ownerRequests': 'ਮਾਲਕ ਅਨੁਰੋਧ', 'admin.ownerRequestsTitle': 'ਮਾਲਕ ਅਨੁਰੋਧ', 'admin.ownerRequestsDescription': 'ਮਾਲਕ ਸਤਿਆਪਨ ਅਨੁਰੋਧਾਂ ਦੀ ਸਮੀਖਿਆ ਅਤੇ ਪਰਬੰਧ ਕਰੋ।', 'admin.totalRequests': 'ਕੁਲ ਅਨੁਰੋਧ', 'admin.pending': 'ਲੰਬਿਤ', 'admin.approved': 'ਮਨਜ਼ੂਰ', 'admin.requestsList': 'ਅਨੁਰੋਧ ਸੂਚੀ', 'admin.requestsListDescription': 'ਸਾਰੇ ਮਾਲਕ ਅਨੁਰੋਧਾਂ ਨੂੰ ਮਨਜ਼ੂਰ ਅਤੇ ਅਸਵੀਕਾਰ ਕਰਨ ਦੀਆਂ ਕਾਰਵਾਈਆਂ।', 'admin.approve': 'ਮਨਜ਼ੂਰ ਕਰੋ', 'admin.reject': 'ਅਸਵੀਕਾਰ ਕਰੋ', 'admin.noPendingRequests': 'ਕੋਈ ਲੰਬਿਤ ਅਨੁਰੋਧ ਨਹੀਂ।',
    'admin.userProfile': 'ਵਰਤੋਂਕਾਰ ਪ੍ਰੋਫਾਈਲ', 'admin.userProfileTitle': 'ਵਰਤੋਂਕਾਰ ਪ੍ਰੋਫਾਈਲ', 'admin.userDetails': 'ਵਰਤੋਂਕਾਰ ਵਿਵਰਣ', 'admin.name': 'ਨਾਮ', 'admin.email': 'ਈਮੇਲ', 'admin.publicId': 'ਸਾਰਵਜਨਿਕ ID', 'admin.role': 'ਭੂਮਿਕਾ', 'admin.status': 'ਸਥਿਤੀ', 'admin.lastLogin': 'ਆਖਰੀ ਲਾਗਇਨ', 'admin.actions': 'ਕਾਰਵਾਈਆਂ', 'admin.actionsDescription': 'ਇਸ ਵਰਤੋਂਕਾਰ ਤੇ ਪ੍ਰਸ਼ਾਸਨਿਕ ਕਾਰਵਾਈਆਂ ਕਰੋ।', 'admin.activate': 'ਸਰਗਰਮ ਕਰੋ', 'admin.suspend': 'ਨਿਲੰਬਿਤ ਕਰੋ', 'admin.resetPassword': 'ਪਾਸਵਰਡ ਰੀਸੈੱਟ ਕਰੋ', 'admin.sendEmail': 'ਈਮੇਲ ਭੇਜੋ', 'admin.actionSuccess': 'ਕਾਰਵਾਈ ਸਫ਼ਲ ਹੈ', 'admin.actionFailed': 'ਕਾਰਵਾਈ ਅਸਫ਼ਲ ਹੈ',
    'admin.userSearch': 'ਵਰਤੋਂਕਾਰ ਖੋਜ', 'admin.userSearchTitle': 'ਵਰਤੋਂਕਾਰ ਖੋਜ', 'admin.userSearchDescription': 'ਨਾਮ, ਸਾਰਵਜਨਿਕ ID ਜਾਂ ਈਮੇਲ ਰਾਹੀਂ ਵਰਤੋਂਕਾਰਾਂ ਦੀ ਖੋਜ ਕਰੋ।', 'admin.searchPlaceholder': 'ਵਰਤੋਂਕਾਰ ਖੋਜੋ...', 'admin.search': 'ਖੋਜ', 'admin.searching': 'ਖੋਜ ਰਿਹਾ ਹਾਂ...', 'admin.searchResults': 'ਖੋਜ ਨਤੀਜੇ', 'admin.usersFound': 'ਵਰਤੋਂਕਾਰ ਮਿਲੇ', 'admin.noUsersFound': 'ਕੋਈ ਵਰਤੋਂਕਾਰ ਨਹੀਂ ਮਿਲਿਆ।',
    'admin.attendanceRecords': 'ਹਾਜ਼ਰੀ ਰਿਕਾਰਡ', 'admin.attendanceDescription': 'ਹਾਜ਼ਰੀ ਰਿਕਾਰਡ ਵੇਖੋ ਅਤੇ ਪਰਬੰਧ ਕਰੋ।', 'admin.attendanceList': 'ਹਾਜ਼ਰੀ ਸੂਚੀ', 'admin.attendanceListDescription': 'ਸਾਰੇ ਕਰਮਚਾਰੀਆਂ ਲਈ ਮੌਜੂਦਾ ਹਾਜ਼ਰੀ ਰਿਕਾਰਡ।', 'admin.present': 'ਮੌਜੂਦ', 'admin.late': 'ਦੇਰ', 'admin.absent': 'ਅਨੁਪਸਥਿਤ',
    'admin.payrollRecords': 'ਤਨਖਾਹ ਰਿਕਾਰਡ', 'admin.payrollDescription': 'ਤਨਖਾਹ ਰਿਕਾਰਡ ਵੇਖੋ ਅਤੇ ਪਰਬੰਧ ਕਰੋ।', 'admin.payrollList': 'ਤਨਖਾਹ ਸੂਚੀ', 'admin.payrollListDescription': 'ਮੌਜੂਦਾ ਅਵਧੀ ਲਈ ਤਨਖਾਹ ਰਿਕਾਰਡ।', 'admin.totalPayroll': 'ਕੁਲ ਤਨਖਾਹ', 'admin.paid': 'ਭੁਗਤਾਨ ਕੀਤਾ ਗਿਆ',
    'session.restoring': 'ਤੁਹਾਡਾ ਸੁਰੱਖਿਅਤ ਸੈਸ਼ਨ ਬਹਾਲ ਹੋ ਰਿਹਾ ਹੈ…', 'session.signedInAs': 'ਵਜੋਂ ਸਾਈਨ ਇਨ', 'session.signOut': 'ਸਾਈਨ ਆਊਟ', 'session.signingOut': 'ਸਾਈਨ ਆਊਟ ਹੋ ਰਿਹਾ ਹੈ…',
  },
};
