export type Language = 'en' | 'hi' | 'pa';

export const languageLabels: Record<Language, string> = { en: 'English', hi: 'हिन्दी', pa: 'ਪੰਜਾਬੀ' };

export const messages: Record<Language, Record<string, string>> = {
  en: {
    'language.label': 'Language', 'theme.label': 'Theme', 'theme.dark': 'Dark', 'theme.light': 'Light', 'theme.amoled': 'AMOLED', 'theme.system': 'System',
    'nav.overview': 'Overview', 'nav.workforce': 'Workforce', 'nav.sites': 'Sites', 'nav.payroll': 'Payroll', 'nav.ai': 'AI Assistant', 'nav.workforceOs': 'Workforce OS', 'nav.today': 'Today', 'nav.projectPulse': 'Project pulse', 'nav.openCommandCenter': 'Open command center', 'nav.approvalsSummary': '11 approvals pending · 4 sites active',
    'topbar.goodEvening': 'Good evening', 'topbar.controlCenter': 'Operational control center', 'topbar.search': 'Search workforce', 'topbar.sync': 'Sync now',
    'dashboard.operatingSystem': 'Workforce operating system', 'dashboard.heroTitle': 'The calm control layer for the modern jobsite.', 'dashboard.heroDescription': 'Premium operations, field-ready sync, and AI-guided clarity for every crew, site, and approval.', 'dashboard.reviewToday': 'Review today', 'dashboard.openAi': 'Open AI assistant', 'dashboard.siteHealth': 'Site health', 'dashboard.liveSnapshot': 'Live readiness snapshot', 'dashboard.stable': 'Stable', 'dashboard.crewCommute': 'Crew commute', 'dashboard.materials': 'Materials', 'dashboard.equipment': 'Equipment', 'dashboard.todayWorkforce': 'Today’s workforce', 'dashboard.timelineDescription': 'A premium timeline view for crews and approvals', 'dashboard.openTimeline': 'Open timeline', 'dashboard.attendanceSynced': 'Attendance synced', 'dashboard.approvalPending': 'Approval pending', 'dashboard.payrollReview': 'Payroll review', 'dashboard.crewCheckedIn': 'Crew A · 24 checked in', 'dashboard.materialRequest': 'Materials request · Site 12', 'dashboard.weeklyRunReady': 'Weekly run ready', 'dashboard.aiInsight': 'AI insight', 'dashboard.aiDescription': 'Refined for operators, not gimmicks', 'dashboard.live': 'Live', 'dashboard.aiMessage': 'Two crews will likely exceed overtime thresholds by 2.6% this week. Recommend a dispatch adjustment.',
    'metric.workersPresent': 'Workers present', 'metric.payrollDue': 'Payroll due', 'metric.sitesHealthy': 'Sites healthy', 'metric.expenses': 'Expenses', 'metric.pending': '4 pending', 'metric.alerts': '3 alerts', 'metric.today': 'Today', 'common.view': 'View', 'common.createFirstItem': 'Create first item',
  },
  hi: {
    'language.label': 'भाषा', 'theme.label': 'थीम', 'theme.dark': 'डार्क', 'theme.light': 'लाइट', 'theme.amoled': 'AMOLED', 'theme.system': 'सिस्टम',
    'nav.overview': 'अवलोकन', 'nav.workforce': 'कार्यबल', 'nav.sites': 'साइट', 'nav.payroll': 'पेरोल', 'nav.ai': 'AI सहायक', 'nav.workforceOs': 'कार्यबल OS', 'nav.today': 'आज', 'nav.projectPulse': 'प्रोजेक्ट स्थिति', 'nav.openCommandCenter': 'कमांड सेंटर खोलें', 'nav.approvalsSummary': '11 अनुमोदन लंबित · 4 साइट सक्रिय',
    'topbar.goodEvening': 'शुभ संध्या', 'topbar.controlCenter': 'ऑपरेशनल कंट्रोल सेंटर', 'topbar.search': 'कार्यबल खोजें', 'topbar.sync': 'अभी सिंक करें',
    'dashboard.operatingSystem': 'कार्यबल ऑपरेटिंग सिस्टम', 'dashboard.heroTitle': 'आधुनिक जॉबसाइट के लिए शांत नियंत्रण केंद्र।', 'dashboard.heroDescription': 'हर टीम, साइट और अनुमोदन के लिए प्रीमियम ऑपरेशन, फील्ड-रेडी सिंक और AI मार्गदर्शन।', 'dashboard.reviewToday': 'आज की समीक्षा करें', 'dashboard.openAi': 'AI सहायक खोलें', 'dashboard.siteHealth': 'साइट स्थिति', 'dashboard.liveSnapshot': 'लाइव तैयारी सारांश', 'dashboard.stable': 'स्थिर', 'dashboard.crewCommute': 'टीम आवागमन', 'dashboard.materials': 'सामग्री', 'dashboard.equipment': 'उपकरण', 'dashboard.todayWorkforce': 'आज का कार्यबल', 'dashboard.timelineDescription': 'टीम और अनुमोदन की टाइमलाइन', 'dashboard.openTimeline': 'टाइमलाइन खोलें', 'dashboard.attendanceSynced': 'उपस्थिति सिंक हुई', 'dashboard.approvalPending': 'अनुमोदन लंबित', 'dashboard.payrollReview': 'पेरोल समीक्षा', 'dashboard.crewCheckedIn': 'टीम A · 24 उपस्थित', 'dashboard.materialRequest': 'सामग्री अनुरोध · साइट 12', 'dashboard.weeklyRunReady': 'साप्ताहिक रन तैयार', 'dashboard.aiInsight': 'AI जानकारी', 'dashboard.aiDescription': 'ऑपरेटरों के लिए स्पष्ट और उपयोगी', 'dashboard.live': 'लाइव', 'dashboard.aiMessage': 'इस सप्ताह दो टीमें ओवरटाइम सीमा से 2.6% अधिक जा सकती हैं। डिस्पैच समायोजन सुझाया गया है।',
    'metric.workersPresent': 'उपस्थित कर्मचारी', 'metric.payrollDue': 'पेरोल देय', 'metric.sitesHealthy': 'सक्रिय साइट', 'metric.expenses': 'खर्च', 'metric.pending': '4 लंबित', 'metric.alerts': '3 अलर्ट', 'metric.today': 'आज', 'common.view': 'देखें', 'common.createFirstItem': 'पहली प्रविष्टि बनाएँ',
  },
  pa: {
    'language.label': 'ਭਾਸ਼ਾ', 'theme.label': 'ਥੀਮ', 'theme.dark': 'ਡਾਰਕ', 'theme.light': 'ਲਾਈਟ', 'theme.amoled': 'AMOLED', 'theme.system': 'ਸਿਸਟਮ',
    'nav.overview': 'ਝਲਕ', 'nav.workforce': 'ਕਰਮਚਾਰੀ', 'nav.sites': 'ਸਾਈਟਾਂ', 'nav.payroll': 'ਤਨਖਾਹ', 'nav.ai': 'AI ਸਹਾਇਕ', 'nav.workforceOs': 'ਕਰਮਚਾਰੀ OS', 'nav.today': 'ਅੱਜ', 'nav.projectPulse': 'ਪ੍ਰੋਜੈਕਟ ਸਥਿਤੀ', 'nav.openCommandCenter': 'ਕਮਾਂਡ ਸੈਂਟਰ ਖੋਲ੍ਹੋ', 'nav.approvalsSummary': '11 ਮਨਜ਼ੂਰੀਆਂ ਲੰਬਿਤ · 4 ਸਾਈਟਾਂ ਸਰਗਰਮ',
    'topbar.goodEvening': 'ਸ਼ੁਭ ਸ਼ਾਮ', 'topbar.controlCenter': 'ਓਪਰੇਸ਼ਨਲ ਕੰਟਰੋਲ ਸੈਂਟਰ', 'topbar.search': 'ਕਰਮਚਾਰੀ ਲੱਭੋ', 'topbar.sync': 'ਹੁਣੇ ਸਿੰਕ ਕਰੋ',
    'dashboard.operatingSystem': 'ਕਰਮਚਾਰੀ ਓਪਰੇਟਿੰਗ ਸਿਸਟਮ', 'dashboard.heroTitle': 'ਆਧੁਨਿਕ ਜੌਬਸਾਈਟ ਲਈ ਸ਼ਾਂਤ ਕੰਟਰੋਲ ਪਰਤ।', 'dashboard.heroDescription': 'ਹਰ ਟੀਮ, ਸਾਈਟ ਅਤੇ ਮਨਜ਼ੂਰੀ ਲਈ ਪ੍ਰੀਮੀਅਮ ਓਪਰੇਸ਼ਨ, ਫੀਲਡ-ਤਿਆਰ ਸਿੰਕ ਅਤੇ AI ਮਾਰਗਦਰਸ਼ਨ।', 'dashboard.reviewToday': 'ਅੱਜ ਦੀ ਸਮੀਖਿਆ ਕਰੋ', 'dashboard.openAi': 'AI ਸਹਾਇਕ ਖੋਲ੍ਹੋ', 'dashboard.siteHealth': 'ਸਾਈਟ ਸਥਿਤੀ', 'dashboard.liveSnapshot': 'ਲਾਈਵ ਤਿਆਰੀ ਸਾਰ', 'dashboard.stable': 'ਸਥਿਰ', 'dashboard.crewCommute': 'ਟੀਮ ਆਵਾਜਾਈ', 'dashboard.materials': 'ਸਮੱਗਰੀ', 'dashboard.equipment': 'ਸਾਜ਼ੋ-ਸਾਮਾਨ', 'dashboard.todayWorkforce': 'ਅੱਜ ਦਾ ਕਰਮਚਾਰੀ ਦਲ', 'dashboard.timelineDescription': 'ਟੀਮਾਂ ਅਤੇ ਮਨਜ਼ੂਰੀਆਂ ਦੀ ਟਾਈਮਲਾਈਨ', 'dashboard.openTimeline': 'ਟਾਈਮਲਾਈਨ ਖੋਲ੍ਹੋ', 'dashboard.attendanceSynced': 'ਹਾਜ਼ਰੀ ਸਿੰਕ ਹੋਈ', 'dashboard.approvalPending': 'ਮਨਜ਼ੂਰੀ ਲੰਬਿਤ', 'dashboard.payrollReview': 'ਤਨਖਾਹ ਸਮੀਖਿਆ', 'dashboard.crewCheckedIn': 'ਟੀਮ A · 24 ਹਾਜ਼ਰ', 'dashboard.materialRequest': 'ਸਮੱਗਰੀ ਬੇਨਤੀ · ਸਾਈਟ 12', 'dashboard.weeklyRunReady': 'ਹਫ਼ਤਾਵਾਰੀ ਰਨ ਤਿਆਰ', 'dashboard.aiInsight': 'AI ਜਾਣਕਾਰੀ', 'dashboard.aiDescription': 'ਆਪਰੇਟਰਾਂ ਲਈ ਸਾਫ਼ ਅਤੇ ਲਾਭਦਾਇਕ', 'dashboard.live': 'ਲਾਈਵ', 'dashboard.aiMessage': 'ਇਸ ਹਫ਼ਤੇ ਦੋ ਟੀਮਾਂ ਓਵਰਟਾਈਮ ਹੱਦ ਤੋਂ 2.6% ਵੱਧ ਜਾ ਸਕਦੀਆਂ ਹਨ। ਡਿਸਪੈਚ ਬਦਲਾਅ ਦੀ ਸਿਫ਼ਾਰਸ਼ ਹੈ।',
    'metric.workersPresent': 'ਹਾਜ਼ਰ ਕਰਮਚਾਰੀ', 'metric.payrollDue': 'ਤਨਖਾਹ ਬਕਾਇਆ', 'metric.sitesHealthy': 'ਸਰਗਰਮ ਸਾਈਟਾਂ', 'metric.expenses': 'ਖਰਚੇ', 'metric.pending': '4 ਲੰਬਿਤ', 'metric.alerts': '3 ਚੇਤਾਵਨੀਆਂ', 'metric.today': 'ਅੱਜ', 'common.view': 'ਵੇਖੋ', 'common.createFirstItem': 'ਪਹਿਲੀ ਐਂਟਰੀ ਬਣਾਓ',
  },
};
